#!/bin/sh
echo "Enter filename:"
read file
w=`cat $file | wc -w`
c=`cat $file | wc -c`
l=`grep -c \".\" $file`
echo Number of characters in $file = $c
echo Number of words in $file = $w
echo Number of lines in $file = $l
