#!/bin/sh
echo "1. add"
echo "2. sub"
echo "3. mul"
echo "4. div"
echo "select your choice(1-4) "
read choice
if [ $choice -eq 1 ]
then
echo " enter 2 numbers "
read a b
result=`expr "$a+$b"|bc`
echo "Result= $result "
elif [ $choice -eq 2 ]
then
echo " enter 2 numbers "
read a b
result=`expr "$a-$b"|bc`
echo "Result= $result "
elif [ $choice -eq 3 ]
then
echo " enter 2 numbers "
read a b
result=`expr "$a*$b"|bc`
echo "Result= $result "
elif [ $choice -eq 4 ]
then
echo " enter 2 numbers "
read a b
result=`expr "$a/$b"|bc`
echo "Result= $result "
else
echo "wrong choice"
fi
